### ISSUE TITLE
RuntimeError: Can't determine home directory

### ISSUE THREAD

**Issue by moligaCUG** [chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT#5]
作者你好，我在window上的git bash中运行./make.sh的时候遇到了如下报错：$ ./make.sh
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    setup(
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\__init__.py", line 102, in setup
    _install_setup_requires(attrs)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\__init__.py", line 73, in _install_setup_requires
    dist.parse_config_files(ignore_option_errors=True)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\dist.py", line 647, in parse_config_files
    self._parse_config_files(filenames=inifiles)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\dist.py", line 477, in _parse_config_files
    filenames = self.find_config_files()
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\dist.py", line 338, in find_config_files
    files = [str(path) for path in self._gen_paths() if os.path.isfile(path)]
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\dist.py", line 338, in <listcomp>
    files = [str(path) for path in self._gen_paths() if os.path.isfile(path)]
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\dist.py", line 354, in _gen_paths
    yield pathlib.Path('~').expanduser() / filename
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\pathlib.py", line 1556, in expanduser
    homedir = self._flavour.gethomedir(self._parts[0][1:])
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\pathlib.py", line 266, in gethomedir
    raise RuntimeError("Can't determine home directory")
RuntimeError: Can't determine home directory
请问有解决的办法吗？我按照前文要求创建了虚拟环境和配置了对应版本的pytorch等

**Comment by chen-si-jia** [comment]
> 作者你好，我在window上的git bash中运行./make.sh的时候遇到了如下报错：$ ./make.sh Traceback (most recent call last): File "setup.py", line 55, in setup( File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools__init__.py", line 102, in setup _install_setup_requires(attrs) File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools__init__.py", line 73, in _install_setup_requires dist.parse_config_files(ignore_option_errors=True) File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\dist.py", line 647, in parse_config_files self._parse_config_files(filenames=inifiles) File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\dist.py", line 477, in _parse_config_files filenames = self.find_config_files() File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools_distutils\dist.py", line 338, in find_config_files files = [str(path) for path in self._gen_paths() if os.path.isfile(path)] File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools_distutils\dist.py", line 338, in files = [str(path) for path in self._gen_paths() if os.path.isfile(path)] File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools_distutils\dist.py", line 354, in _gen_paths yield pathlib.Path('~').expanduser() / filename File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\pathlib.py", line 1556, in expanduser homedir = self._flavour.gethomedir(self._parts[0][1:]) File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\pathlib.py", line 266, in gethomedir raise RuntimeError("Can't determine home directory") RuntimeError: Can't determine home directory 请问有解决的办法吗？我按照前文要求创建了虚拟环境和配置了对应版本的pytorch等

Windows下面运行.sh文件需要进行专门的配合。我们的代码是在linux（ubuntu）系统下进行运行的，建议配置和我们代码相同的系统。
